### ISSUE TITLE
(french) How to disable Post-Process Effect because of bad performance?

### ISSUE THREAD

**Issue by Augaton** [Guthen/guthscp096#7]
Ajouter une option pour désactiver le voile qu'il y a sur le swep car sa tue les fps et c'est assez dommage (après il y a sûrement une solution pour éviter ce genre de chute de fps)

**Comment by Guthen** [comment]
Est-ce que par "voile" tu parles des effets post-process quand tu joues 096?

Si oui, y a déjà une convar à rentrer pour les désactiver : `vkx_scp096_render_post_process 0` (ça prend effet uniquement sur le joueur qui l'a rentré, pas pour tout le monde)

**Comment by Augaton** [comment]
Oui je parler du voile quand il était inactif et que donc personne ne le regarder
Mais sinon pas de problème,  je te remercie !
